stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - apt-get update -qy
    - apt-get install -y g++ make jq

test:
    image: python:3.8
    stage: test
    script:
        - bash recompile.sh
        - time ./ikpx2 -x 6 -p 1 -v 'c/3' | tee -i results.txt
        - grep xq3_3u0228mc53bgzof0882d6koq1 results.txt
